//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ShellTime.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SHELLTIME_DIALOG            102
#define IDS_TIPTEXT                     102
#define IDS_HOURS                       103
#define IDS_HOUR                        104
#define IDS_MINUTES                     105
#define IDS_MINUTE                      106
#define IDS_DAYS                        107
#define IDS_DAY                         108
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       130
#define IDR_CONTEXT                     131
#define IDD_DETAILS                     132
#define IDC_HYPERLINKCURSOR             133
#define IDC_UPTIMEEDIT                  1000
#define IDC_REBOOTEDIT                  1001
#define IDC_HOMEPAGE                    1001
#define ID_TOP_EXIT                     32771
#define ID_TOP_ABOUT                    32772
#define ID_TOP_DETAILS                  32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
